package com.minecraftindustrialcomplex.mic_climate.gametest;

import com.minecraftindustrialcomplex.mic_climate.Compat;
import com.minecraftindustrialcomplex.mic_climate.MicClimate;
import net.minecraft.gametest.framework.GameTestAssertException;
import net.minecraft.gametest.framework.GameTestHelper;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.event.RegisterGameTestsEvent;

import java.util.Locale;

/**
 * The suite's entry point, and the only class outside this package that the mod
 * names.
 *
 * <p><b>Why the holders are split.</b> Almost everything worth asserting about
 * this mod is a claim about another mod — "Power Grid's ambient now equals ours",
 * "Destroy's local temperature now equals ours". One holder per bridged mod
 * keeps each of those claims next to the imports it needs and makes a missing
 * mod a set of skips rather than a wall of errors.
 *
 * <p><b>Who registers them.</b> NeoForge does, on its own: it collects
 * {@code @GameTestHolder} classes out of each mod's annotation scan data, so
 * every holder here is queued regardless of which optional mods are present.
 * That is why the gating is per test ({@link #skipWithout}) and not per class,
 * and why the code that touches an optional mod always sits in a method or a
 * class of its own -- so the JVM never verifies a body it cannot resolve.
 *
 * <p><b>Batching.</b> {@code ClimateConfig.Test} overrides, the level's
 * pollution and Project Atmosphere's regional state are all process- or
 * world-wide, and tests within one gametest batch run <em>simultaneously</em>.
 * Every test that writes any of them therefore declares a {@code batch} of its
 * own; batches run one after another. Tests that only read share the default
 * batch.
 */
public final class GameTests {

    /**
     * The structure every test runs in: a 5x5x5 box of air on a one-block floor
     * ({@code data/mic_climate/structure/empty_5x5x5.nbt}, generated by
     * {@code tools/make_test_structure.py}).
     *
     * <p>A structure is not optional. NeoForge 21.1's gametest path goes through
     * vanilla's {@code StructureUtils.prepareTestStructure}, which throws
     * {@code IllegalStateException("Missing test structure")} on an empty
     * template name; the {@code @EmptyTemplate} annotation belongs to NeoForge's
     * separate test framework, which is not on this classpath.
     */
    public static final String TEMPLATE = "empty_5x5x5";

    /** Middle of the box, one block clear of the floor and of every wall. */
    public static final net.minecraft.core.BlockPos CENTRE = new net.minecraft.core.BlockPos(2, 1, 2);

    /** Somewhere to put a device without standing it on the position under test. */
    public static final net.minecraft.core.BlockPos DEVICE = new net.minecraft.core.BlockPos(0, 1, 0);

    /** The sibling addon; it has no constant in {@code Compat} because the mod itself never asks. */
    public static final String MIC_DESTROY_ELECTRIC = "mic_destroy_electric";

    private GameTests() {}

    public static void init(IEventBus modBus) {
        if (!enabled())
            return;
        modBus.addListener(RegisterGameTestsEvent.class, GameTests::onRegister);
    }

    /**
     * Reports what this run can actually assert.
     *
     * <p>It deliberately does <b>not</b> register anything. NeoForge finds
     * {@code @GameTestHolder} classes itself, from the mod's annotation scan
     * data, so every holder in this package is queued whether or not the mod it
     * is about is installed -- which is why each optional test starts with
     * {@link #skipWithout} rather than relying on a registration-time guard.
     * This listener exists so the log says up front which bridges had something
     * to bind to, instead of leaving that to be inferred from skips.
     */
    private static void onRegister(RegisterGameTestsEvent event) {
        MicClimate.LOGGER.info("[gametest] suite enabled for namespace {}", MicClimate.MODID);
        for (String modid : new String[] {
                Compat.POWERGRID, Compat.DESTROY, Compat.LEGENDARY_SURVIVAL_OVERHAUL,
                Compat.PROJECT_ATMOSPHERE, Compat.CROWNS, Compat.THERMOO_PATCHES,
                MIC_DESTROY_ELECTRIC
        }) {
            MicClimate.LOGGER.info("[gametest] bridged mod {}: {}",
                    modid, Compat.isLoaded(modid) ? "present" : "ABSENT (its tests will skip)");
        }
    }

    /**
     * Skips the calling test, as a pass, when a mod it is about is missing.
     *
     * <p>Must be the first statement of the test method, and the code that
     * touches that mod must live in another method or class, so that the JVM
     * never has to verify a body full of names it cannot resolve.
     */
    public static boolean skipWithout(GameTestHelper helper, String modid) {
        if (Compat.isLoaded(modid))
            return false;
        MicClimate.LOGGER.warn("[gametest] SKIPPED: {} is not installed", modid);
        helper.succeed();
        return true;
    }

    // ------------------------------------------------------------------
    // Assertions.
    //
    // Every one of them logs the numbers it compared, pass or fail. The point of
    // this suite is not only "did it pass" but "what did Power Grid actually
    // say", and a green run whose log does not contain the values it agreed on
    // proves much less than one that does.
    // ------------------------------------------------------------------

    /** Asserts two temperatures agree, and records both either way. */
    public static void assertNear(String what, double actual, double expected, double tolerance) {
        double difference = Math.abs(actual - expected);
        String line = String.format(
                Locale.ROOT,
                "[gametest] %s: actual=%.4f expected=%.4f diff=%.4f tolerance=%.4f",
                what, actual, expected, difference, tolerance
        );
        if (difference <= tolerance) {
            MicClimate.LOGGER.info("{} OK", line);
            return;
        }
        MicClimate.LOGGER.error("{} FAILED", line);
        throw new GameTestAssertException(line + " FAILED");
    }

    /** Asserts a value is at least {@code minimum}, and records it either way. */
    public static void assertAtLeast(String what, double actual, double minimum) {
        String line = String.format(
                Locale.ROOT, "[gametest] %s: actual=%.4f minimum=%.4f", what, actual, minimum);
        if (actual >= minimum) {
            MicClimate.LOGGER.info("{} OK", line);
            return;
        }
        MicClimate.LOGGER.error("{} FAILED", line);
        throw new GameTestAssertException(line + " FAILED");
    }

    public static void assertTrue(String what, boolean condition) {
        if (condition) {
            MicClimate.LOGGER.info("[gametest] {}: OK", what);
            return;
        }
        MicClimate.LOGGER.error("[gametest] {}: FAILED", what);
        throw new GameTestAssertException("[gametest] " + what + " FAILED");
    }

    /** Notes an observation that is evidence rather than a pass/fail claim. */
    public static void record(String what, Object value) {
        MicClimate.LOGGER.info("[gametest] {} = {}", what, value);
    }

    /** The absolute position of {@link #CENTRE} for this test's instance. */
    public static net.minecraft.core.BlockPos centre(GameTestHelper helper) {
        return helper.absolutePos(CENTRE);
    }

    /**
     * True when this JVM was launched to run the suite: either by the
     * {@code gameTestServer} Gradle run (which sets {@code mic_climate.gametest})
     * or by anything else that has asked NeoForge to enable our namespace.
     */
    private static boolean enabled() {
        if (Boolean.getBoolean("mic_climate.gametest"))
            return true;
        for (String namespace : System.getProperty("neoforge.enabledGameTestNamespaces", "").split(",")) {
            if (namespace.trim().equals(MicClimate.MODID))
                return true;
        }
        return false;
    }
}
